### ISSUE TITLE
Error while creating new source

### ISSUE THREAD

**Issue by fervid** [StamusNetworks/scirius#53]
Hello.
I try to create source. I filled in all necessary fields in form:
![submit et open](https://cloud.githubusercontent.com/assets/1450910/9845018/b26478e0-5ad0-11e5-818a-ca8ba294d2a7.png)

Then clicked update and got error in some time:
![et error](https://cloud.githubusercontent.com/assets/1450910/9845020/b5a8dc08-5ad0-11e5-8989-3c702b6a913a.png)

Version of suricata: 2.0.6.
OS: ubuntu 15.04-server.

**Comment by regit** [comment]
Hi,

Do you have suricata in the path of user running scirius ? Source test system is needing a working suricata to do the testing. Problem is that scirius needs a really recent suricata to work well. I will try to improve that but for now you can simply ignore the alert message.

**Comment by fervid** [comment]
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

which suricata
/usr/bin/suricata

**Comment by regit** [comment]
Sorry for the delay.

I have pushed some patches on master to fix the issue. My test seems to show that it is working correctly.

@fervid could you let me know if it is working now.

**Comment by fervid** [comment]
Hi. It still doesn't work...
![screenshot from 2015-10-27 14 37 16](https://cloud.githubusercontent.com/assets/1450910/10756937/5486375e-7cb8-11e5-86f4-db97d71efaf1.png)

**Comment by pevma** [comment]
This means that this particular rule did not load. It is not a "show stopper"
You can click on "Ignore erros and continue".

**Comment by fervid** [comment]
But if I click on any category I will get empty list of rules...

![screenshot from 2015-10-28 13 39 34](https://cloud.githubusercontent.com/assets/1450910/10786090/734f9a24-7d79-11e5-8c27-5847316b570b.png)

**Comment by regit** [comment]
from what I read on the screenshot, this is ET ruleset ? Is this the PRO version ?

**Comment by fervid** [comment]
It is ET free. 
But what is interesting after I updated suricata to 2.0.9 rules became avaliable in this list.

**Comment by regit** [comment]
OK, so you mean that now you've got rules in the list (so it is working) but with an older suricata it was not working ?

**Comment by fervid** [comment]
I am not sure, but it seems so.

**Comment by regit** [comment]
Closing it as it was working at last comment.
